import express from 'express';
import multer from 'multer';
import { verifyToken } from '../middleware/verifyToken.js';
import { saveQr, deleteQrs, getUserQrs, scanQr, getUserQrScans, getTop10UserQrs, getLastWeekStats } from '../controllers/qr.controller.js';
const router = express.Router();
const storage = multer.memoryStorage(); 
const upload = multer({ storage });
router.post('/save', verifyToken, upload.single('logo'), saveQr);
router.delete('/delete', verifyToken, deleteQrs);
router.get('/user/:userId', verifyToken, getUserQrs);
router.get('/scan/:tokenURL',scanQr);
router.get('/QrUserScan/:userId',verifyToken,getUserQrScans);
router.get('/TopScans/:userId',verifyToken,getTop10UserQrs);
router.get('/weeklyStats/:userId',verifyToken,getLastWeekStats);
export default router;