import express from 'express';
import multer from 'multer';
import { verifyToken } from '../middleware/verifyToken.js';
import { saveQr, deleteQrs } from '../controllers/qr.controller.js';
const router = express.Router();
const storage = multer.memoryStorage(); 
const upload = multer({ storage });
router.post('/save', verifyToken, upload.single('logo'), saveQr);
router.delete('/delete', verifyToken, deleteQrs);
export default router;